### ISSUE TITLE
Carto layers not working -- "Cannot access system tables"

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial-map-library#116]
Seem like Carto pulled the plug on letting API queries access system tables.

**Comment by nateirwin** [comment]
Ugh

**Comment by nateirwin** [comment]
Still seeing this error in Map Builder production.

**Comment by nateirwin** [comment]
Oops, just noticed this is in Map Library. I'm beginning to think we need to come up with a way of tying Map Library and Map Builder development together more closely so we can sync up enhancements/fixes. I know that would make things a lot less confusing for everyone. I'll go ahead and close this though... since it's been fixed here just not deployed into Map Builder yet.

Sorry about the confusion!
