### ISSUE TITLE
Hitting the "Enter" key when the geocoderControl textfield is focused searches twice

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#152]

**Comment by ryanjhodge** [comment]
So currently, if i type in a word and press enter, then a geocode provider search is performed. Is that the behavior we want to avoid? This also happens when the magnifying glass is clicked. 

On enter keydown event should we check if there are any search results, and if so select the first result instead of sending the geocode request. or perhaps move the focus to the search list?

**Comment by nateirwin** [comment]
We definitely want "Enter" to perform a geocode search. But currently hitting "Enter" does two geocode searches. It isn't evident from the UI, but if you add a breakpoint where the geocode search is executed, you should see the problem.
