### ISSUE TITLE
Make Google directions work on mobile when Google Maps is installed

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial-map-library#68]
Initially opened [here](https://github.com/trailheadlabs/outerspatial/issues/1444), but moving here because this is a Map Library issue.

**Comment by ryanjhodge** [comment]
I'm unable to reproduce on Android.  I used the map originally provided (https://www.outerspatial.com/builder_maps/40/embed) and also the geojson layer dev example. It opens the google maps app when I click on the link.

Also a side note: When I choose bing, the google maps app opens with an empty destination. Not sure if Andorid is intercepting it or if it has to do with default app settings.  I tried clearing my default app preferences and still the same behavior.

**Comment by nateirwin** [comment]
On iOS, clicking "Google" takes me to the Google Maps website, which is ok. Not sure why it's not launching the app though, as it is installed on my phone.

Clicking "Bing", oddly enough, asks me to open Apple Maps and then opens the Apple Maps app, but doesn't properly fill out the destination.

**Comment by ryanjhodge** [comment]
(See comment here)[https://stackoverflow.com/questions/18739436/how-to-create-a-link-for-all-mobile-devices-that-opens-google-maps-with-a-route#comment68277964_18899718]

It seems that apple links are widely supported across platforms:
http://maps.apple.com/?daddr=39.743648,-104.995189
I tested the following cases:
- iOS Chrome/Safari -> Opens Apple maps app
- MacOS Chrome/Safari -> Opens Apple maps app
- Android Chrome w/ Google Maps app installed -> Opens Google Maps App
- Android Chome w/o Google Maps app installed -> Opens Google Maps in chrome browser
- Android Samsung Browser w/ and w/o Google Maps app installed -> Opens Google Maps in Samsung Browser
- Windows 10 IE/Edge -> Opens Google Maps in IE/Edge browser

In all cases the destination field was correctly filled out in the routing options of the given application.

Discussed with @nateirwin and we figured the best course of action is to drop Bing and Google map url support and default to apple urls since they are widely supported across platforms and behave consistently.

**Comment by ryanbranciforte** [comment]
@nateirwin and @ryanjhodge I know that a few customers have expressed a strong preference for google maps. How would you feel about having google and apple option? The customers can test and decide for themselves what works best for them.

**Comment by nateirwin** [comment]
There's no way to detect if Google Maps is installed on iOS from a web page. The approach @ryanjhodge outlined should use the mapping app that is setup as a default on an iOS device. This is honestly the best we can do. Web maps are not native apps, so there's only so much we can do.

**Comment by ryanbranciforte** [comment]
How about for on desktop? If we go with Apple maps for directions, what does it open up on the desktop browser?

**Comment by nateirwin** [comment]
@ryanjhodge outlines the behavior on all device/browsers here: https://github.com/trailheadlabs/outerspatial-map-library/issues/68#issuecomment-341517681

**Comment by ryanbranciforte** [comment]
Ok, see that. To be honest, I didn't even know there was a apple map option for desktop. 

I still vote for leaving Google and Apple as options and then let the customer decide or we set it to apple be default for them.

**Comment by nateirwin** [comment]
The point is we can't do that and make it work consistently on mobile. This is the only way we've figured out how to make it work consistently on both desktop and mobile.

Plus, having an "Apple" option when you're on a non-OS X laptop/desktop doesn't make any sense.

**Comment by nateirwin** [comment]
Yeah, I think getting it out there and getting customer feedback is best. This approach may not be perfect, but at least we know it will work consistently across all different devices/operating systems. We can revisit and get fancy, if needed, after hearing from our customers, but don't think it makes sense to spend a ton of time on it up front without having specific requirements in mind.

**Comment by ryanbranciforte** [comment]
👍

**Comment by ryanbranciforte** [comment]
One big drawback of the new directions option is that Apple Maps doesn't offer biking directions on mobile and on desktop it doesn't offer biking, transit or rideshare.
